/*
 * Midgard Public API
 *
 * The Midgard Public API queries THORChain and any chains linked via the Bifröst and prepares information about the network to be readily available for public users. The API parses transaction event data from THORChain and stores them in a time-series database to make time-dependent queries easy. Midgard does not hold critical information. To interact with BEPSwap and Asgardex, users should query THORChain directly.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockRewards {
    #[serde(rename = "blockReward", skip_serializing_if = "Option::is_none")]
    pub block_reward: Option<String>,
    #[serde(rename = "bondReward", skip_serializing_if = "Option::is_none")]
    pub bond_reward: Option<String>,
    #[serde(rename = "stakeReward", skip_serializing_if = "Option::is_none")]
    pub stake_reward: Option<String>,
}

impl BlockRewards {
    pub fn new() -> BlockRewards {
        BlockRewards {
            block_reward: None,
            bond_reward: None,
            stake_reward: None,
        }
    }
}


