/*
 * Midgard Public API
 *
 * The Midgard Public API queries THORChain and any chains linked via the Bifröst and prepares information about the network to be readily available for public users. The API parses transaction event data from THORChain and stores them in a time-series database to make time-dependent queries easy. Midgard does not hold critical information. To interact with BEPSwap and Asgardex, users should query THORChain directly.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeKey {
    /// secp256k1 public key
    #[serde(rename = "secp256k1", skip_serializing_if = "Option::is_none")]
    pub secp256k1: Option<String>,
    /// ed25519 public key
    #[serde(rename = "ed25519", skip_serializing_if = "Option::is_none")]
    pub ed25519: Option<String>,
}

impl NodeKey {
    pub fn new() -> NodeKey {
        NodeKey {
            secp256k1: None,
            ed25519: None,
        }
    }
}


