/*
 * Midgard Public API
 *
 * The Midgard Public API queries THORChain and any chains linked via the Bifröst and prepares information about the network to be readily available for public users. The API parses transaction event data from THORChain and stores them in a time-series database to make time-dependent queries easy. Midgard does not hold critical information. To interact with BEPSwap and Asgardex, users should query THORChain directly.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Option {
    #[serde(rename = "priceTarget", skip_serializing_if = "Option::is_none")]
    pub price_target: Option<String>,
    #[serde(rename = "withdrawBasisPoints", skip_serializing_if = "Option::is_none")]
    pub withdraw_basis_points: Option<String>,
    #[serde(rename = "asymmetry", skip_serializing_if = "Option::is_none")]
    pub asymmetry: Option<String>,
}

impl Option {
    pub fn new() -> Option {
        Option {
            price_target: None,
            withdraw_basis_points: None,
            asymmetry: None,
        }
    }
}


