/*
 * Midgard Public API
 *
 * The Midgard Public API queries THORChain and any chains linked via the Bifröst and prepares information about the network to be readily available for public users. The API parses transaction event data from THORChain and stores them in a time-series database to make time-dependent queries easy. Midgard does not hold critical information. To interact with BEPSwap and Asgardex, users should query THORChain directly.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThorchainConstants {
    #[serde(rename = "int_64_values", skip_serializing_if = "Option::is_none")]
    pub int_64_values: Option<crate::models::ThorchainInt64Constants>,
    #[serde(rename = "bool_values", skip_serializing_if = "Option::is_none")]
    pub bool_values: Option<crate::models::ThorchainBooleanConstants>,
    #[serde(rename = "string_values", skip_serializing_if = "Option::is_none")]
    pub string_values: Option<crate::models::ThorchainStringConstants>,
}

impl ThorchainConstants {
    pub fn new() -> ThorchainConstants {
        ThorchainConstants {
            int_64_values: None,
            bool_values: None,
            string_values: None,
        }
    }
}


