/*
 * Midgard Public API
 *
 * The Midgard Public API queries THORChain and any chains linked via the Bifröst and prepares information about the network to be readily available for public users. The API parses transaction event data from THORChain and stores them in a time-series database to make time-dependent queries easy. Midgard does not hold critical information. To interact with BEPSwap and Asgardex, users should query THORChain directly.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: devs@thorchain.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThorchainStringConstants {
    #[serde(rename = "DefaultPoolStatus", skip_serializing_if = "Option::is_none")]
    pub default_pool_status: Option<String>,
}

impl ThorchainStringConstants {
    pub fn new() -> ThorchainStringConstants {
        ThorchainStringConstants {
            default_pool_status: None,
        }
    }
}


